# Generated by Django 5.1.6 on 2025-02-28 00:13

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')])),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='El apellido solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')])),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')])),
                ('plan', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('prueba', 'Prueba Gratuita'), ('pagado', 'Pagado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('es_recursiva', models.BooleanField(default=False, verbose_name='Es Recurrente')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción')),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('tarjeta', 'Tarjeta de crédito por PayPal'), ('binance', 'Binance'), ('gratis', 'Gratis')], default='paypal', max_length=20)),
                ('es_prueba_gratuita', models.BooleanField(default=False)),
                ('fecha_expiracion_prueba', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['usuario', 'estado'], name='core_subscr_usuario_8e4dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan'], name='core_subscr_plan_688983_idx'),
        ),
    ]
