# Generated by Django 5.1.6 on 2025-03-01 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailverificationtoken_subscription_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=100, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')]),
            preserve_default=False,
        ),
    ]
