# Generated by Django 5.1.6 on 2025-03-05 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscription_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=100, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')]),
        ),
    ]
